@startuml
class Airport
{
    - id : int
    - name : string|null
    - city : string
    - country : string
    + getId() : int
    + getName() : string
    + getCity() : string
    + getCountry() : string
}

class Airline
{
    - id : int
    - name : string
    - alias : string
    - country : string
    - active : boolean
    + getId() : int
    + getName() : string
    + getAlias() : string
    + getCountry() : string
    + getActive() : boolean
}

class Route {
    - airlineId : int
    - airportSourceId : int
    - airportDestinationId : int
    - codeShare : string|null
    - stops : int
    + getAirlineId() : int
    + getAirportSourceId() : int
    + airportDestinationId() : int
    + getCodeShare() : string|null
    + getStops() : int
}

class FileHandler{
    - lines : list<string>
    + FileHandler()
    + read(path : string) : list<string>
}

class AirportManagement{
    - airports : list<Airport>
    - airlines : list<Airline>
    - routes : list<Route>
    + AirportManagement()
    + getAirlinesByCountry(country : String) : list<Airline>
    + getPlacesByAirlineName(airlineName : String) : list<Airport>
    + getPlacesByAirlineCode(airlineCode : String) : list<Airport>
    - getDataForAirports() : list<Airport>
    - getDataForAirlines() : list<Airline>
    - getDataForRoutes() : list<Route>
}

class Main {
    + main()
}
@enduml